# The URL the site will be built for
base_url = "https://ankitnaik.pages.dev"
theme = "linkita"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
header_menu_name = "menu_card"
# Put all your custom variables here
# Replace "your_username" with your username.
[extra.menus]
menu_card = [
  { url = "$BASE_URL/blog/", name = "Posts" },
  { url = "$BASE_URL/categories/", name = "Categories" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  { url = "$BASE_URL/about/", name = "About" },
]

[extra.profiles.ankit]

# The URL of avatar.
# e.g. "icons/github.svg"
avatar_url = "images/ProfilePic.png"

# A description of what is in the avatar.
avatar_alt = ""

# Invert avatar color in dark mode.
# Default value: false
avatar_invert = false

# Profile name.
# Default value: the username
name = "Ankit"

# Profile bio.
# Supports Markdown.
bio = "Hello this is my personal site"
# Social icons.
# "name" should be the file name of "static/icons/*.svg" or
# the icon name of https://simpleicons.org/
# "url" supports "$BASE_URL".
# Other variables: "urls", "title", "titles".
social = [
]
[extra.footer]
# Replace with the correct year.
# Default value: the current year
since = 2025

# Replace with the URL of the license you want.
# No default value. Supports "$BASE_URL".
license_url = "https://github.com/ankitnaik1/ankitnaik/edit/main/LICENSE"

# Replace "Your Name" with your name and "CC BY-SA 4.0" with the name of the license you want.
copyright = "&copy; $YEAR Ankit Naik &vert; [MIT]($LICENSE_URL)"
